version: '3.3'

# uffizzi integration
x-uffizzi:
  ingress:
    service: master
    port: 8080

services:

  master:
    image: "${CRAWLAB_IMAGE}"
    environment:
      CRAWLAB_NODE_MASTER: "Y"
    ports:
      - "8080:8080"
    deploy:
          resources:
            limits:
              memory: 500M